### ISSUE TITLE
/deck milestones

### ISSUE THREAD

**Issue by kevinlul** [DawnbrandBots/bastion-bot#22]
## /deck
- [x] Port overflow handling from Emcee (highlander-style decks particularly affected). Can release initially at this stage. (#27)
- [x] Play around with the labels for ratios to improve appearance and aid localization for the inline layout
- [x] Localization: show the card names in the user's selected language
- [x] Localization: switch the labels to the corresponding language. We should look into appropriate i18n packages instead of handrolling first.
- [x] Attach processed YDK to embed like Emcee (where possible, if ephemerals don't support this).

## Attachments
Slash Commands don't support attachments, so to replicate the other function of the old .deck:
- [ ] Process any YDK that comes in through DMs like /deck (maybe the message can optionally state the language and style?)
- [ ] Process any YDK that is attached to a bot mention, since we will still see those without the Message Intent. Same parameter idea as DMs.

**Comment by kevinlul** [comment]
Third item is actionable based on #47, #52, #53.
Fourth item is part of #46.

**Comment by kevinlul** [comment]
Localisation requirements have been satisfied.

**Comment by kevinlul** [comment]
Slash Commands now support attachments, so the proposed alternate mechanisms AND a command-based implementation are both possible. https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type

**Comment by AlphaKretin** [comment]
For simplicity's sake I think I'd prefer to stick to a command-based implementation now that it's an option, rather than introduce the alternate mechanisms just for this one piece of functionality.

**Comment by kevinlul** [comment]
In this case, using subcommands is probably easiest and more user-friendly than enforcing a oneOf condition between a string option and an attachment option. An existing implementation in this codebase is `/locale get` and `/locale set`

**Comment by AlphaKretin** [comment]
Attachment support is implemented in #153. In this case, output should provide a ydke conversion instead of regurgitating the ydk. Or, like Emcee, the deck output should provide both regardless of input. With both ydeck and ydke now dependencies, this can be added easily enough either after or as part of #153.
